language: php

sudo: false

php:
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

script:
  - bin/dev-phpunit

deploy:
  skip_cleanup: true
  provider: script
  script: bin/live-deploy
  on:
    branch: master
    tags: true
